import { z } from 'zod';
import { body,db,guard,hash,HttpError,json,newToken,limit } from '@/lib/server';
import { quoteById } from '@/content/quotes';
const schema=z.object({id:z.string().uuid(),text:z.string().trim().min(1).max(1500),quoteId:z.string().regex(/^q\d{3}$/).nullable()}).strict();
function token(req:Request){return req.headers.get('cookie')?.match(/(?:^|;\s*)notes_owner=([a-f0-9]{64})(?:;|$)/)?.[1]||null}
function cookie(req:Request,t:string){return {'Set-Cookie':`notes_owner=${t}; Path=/; HttpOnly; SameSite=Strict; Max-Age=31536000${new URL(req.url).protocol==='https:'?'; Secure':''}`}}
async function key(t:string){return crypto.subtle.importKey('raw',await crypto.subtle.digest('SHA-256',new TextEncoder().encode('notes:'+t)),{name:'AES-GCM'},false,['encrypt','decrypt'])}
async function seal(text:string,t:string,id:string){const iv=crypto.getRandomValues(new Uint8Array(12));const value=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:new TextEncoder().encode(id)},await key(t),new TextEncoder().encode(text));return JSON.stringify({iv:Array.from(iv),data:Array.from(new Uint8Array(value))})}
async function open(value:string,t:string,id:string){const v=JSON.parse(value);return new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:new Uint8Array(v.iv),additionalData:new TextEncoder().encode(id)},await key(t),new Uint8Array(v.data)))}
export async function GET(req:Request){return guard(async()=>{const t=token(req)||newToken();const rows=await db().prepare('SELECT id, quote_id, content, updated_at FROM notes WHERE owner_hash=? ORDER BY updated_at DESC LIMIT 200').bind(await hash(t)).all<{id:string;quote_id:string|null;content:string;updated_at:number}>();return json({notes:await Promise.all(rows.results.map(async r=>({id:r.id,quoteId:r.quote_id,text:await open(r.content,t,r.id),updatedAt:r.updated_at})))},200,cookie(req,t))})}
export async function PUT(req:Request){return guard(async()=>{const parsed=schema.safeParse(await body(req));if(!parsed.success)throw new HttpError(400,'请写下 1～1500 字的随记。');const t=token(req);if(!t)throw new HttpError(401,'请刷新随记页面后重试，文字可以先复制保留。');await limit(req,t);const n=parsed.data;if(n.quoteId&&!quoteById(n.quoteId))throw new HttpError(400,'这段原文暂不可用。');const owner=await hash(t),now=Date.now();const existing=await db().prepare('SELECT id FROM notes WHERE id=? AND owner_hash=?').bind(n.id,owner).first();if(!existing){const count=await db().prepare('SELECT count(*) AS n FROM notes WHERE owner_hash=?').bind(owner).first<{n:number}>();if((count?.n||0)>=200)throw new HttpError(400,'随记已达 200 篇，请先整理一些旧随记。')}
const change=await db().prepare('INSERT INTO notes(id,owner_hash,quote_id,content,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET quote_id=excluded.quote_id,content=excluded.content,updated_at=excluded.updated_at WHERE notes.owner_hash=excluded.owner_hash').bind(n.id,owner,n.quoteId,await seal(n.text,t,n.id),now).run();if(!change.meta.changes)throw new HttpError(404,'这篇随记无法访问。');return json({note:{...n,updatedAt:now}},200,cookie(req,t))})}
export async function DELETE(req:Request){return guard(async()=>{const v=z.object({id:z.string().uuid()}).strict().safeParse(await body(req));if(!v.success)throw new HttpError(400,'请选择一篇随记。');const t=token(req);if(!t)throw new HttpError(401,'请刷新页面后重试。');await db().prepare('DELETE FROM notes WHERE id=? AND owner_hash=?').bind(v.data.id,await hash(t)).run();return json({ok:true})})}
