"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { ArrowUpRight, ArrowRight, ArrowLeft, Bookmark, BookmarkCheck, BookOpen, Feather, Leaf, Sparkles, Sun, Wind, Heart, LoaderCircle, Trash2, Check, ThumbsUp, MessageCircle, ExternalLink } from "lucide-react";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Toaster } from "@/components/ui/sonner";
import { toast } from "sonner";
import type { Quote, Topic, Preference } from "@/content/quotes";
type Result={slot:string;quote:Quote;guidance:{origin:"editorial";interpretation:string;small_action:string|null}};
type Reading={id:string;topic:Topic;preference:Preference;bookmarks:{id:string;available:boolean}[];expires_at:number;reveals?:Result[];feedback?:{quote_id:string;fit:string;reason:string|null}[]};
type Stage="home"|"ready"|"opened"|"support"|"expired"|"collection"|"fallback";
const STORE="situation-bookmarks:quotes:v1";
const reasonLabels={situation:"不符合我的情况",pressure:"建议有压力",unclear:"不太看得懂",source:"想核实出处"};
class RequestError extends Error{constructor(public status:number,message:string){super(message)}}
async function api<T=Record<string,unknown>>(path:string,method="GET",data?:unknown){const response=await fetch(path,{method,headers:method!=="GET"?{"Content-Type":"application/json"}:undefined,body:data===undefined?undefined:JSON.stringify(data),cache:"no-store",signal:AbortSignal.timeout(12000)});const result=await response.json().catch(()=>({error:"这次没能读到书页，请重试。"}));if(!response.ok)throw new RequestError(response.status,(result as {error?:string}).error||"这次没能读到书页，请重试。");return result as T}
function getFavorites():string[]{try{const v=JSON.parse(localStorage.getItem(STORE)||"[]");return Array.isArray(v)?[...new Set(v.filter((x:unknown)=>typeof x==="string"&&/^q\d{3}$/.test(x as string)))].slice(0,100) as string[]:[]}catch{return []}}
function message(e:unknown){return e instanceof RequestError?e.message:"连接暂时中断了，请再试一次。"}
function Cover(){return <section className="cover-panel" aria-label="此刻，翻一页"><div className="cover-top"><span>情 境 书 签</span><span className="tiny-star" aria-hidden="true">✳</span></div><div className="cover-copy"><p className="eyebrow">给生活，留一页空白</p><h1>此刻，<br/>翻一页。</h1><p>有些答案，不必急着寻找。<br/>让一句文字，陪你停留片刻。</p></div><div className="cover-bottom"><span className="seal">此刻</span><span>一页文字，一点新的可能。</span></div></section>}
function Source({q}:{q:Quote}){return <details className="quote-source"><summary>原文出处与白话含义</summary><p>{q.meaning}</p><p>{q.location}。页面采用简体字展示。</p><a href={q.source} target="_blank" rel="noopener noreferrer">查看原作 <ExternalLink size={12}/></a><p>文字核对：{q.verifiedAt} · 古典原文节选</p></details>}
export default function Home(){
 const [stage,setStage]=useState<Stage>("home");const [text,setText]=useState("");const [mode,setMode]=useState<Preference>("auto");const [reading,setReading]=useState<Reading|null>(null);const [result,setResult]=useState<Result|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [favorites,setFavorites]=useState<string[]>([]);const [savedQuotes,setSavedQuotes]=useState<Quote[]>([]);const [collectionBusy,setCollectionBusy]=useState(false);const [collectionError,setCollectionError]=useState("");const [dialog,setDialog]=useState<"about"|"privacy"|null>(null);const [detail,setDetail]=useState<Quote|null>(null);const [feedback,setFeedback]=useState<Record<string,{fit:string;reason:string|null}>>({});const [feedbackBusy,setFeedbackBusy]=useState(false);const [skipMotion,setSkipMotion]=useState(false);
 const resultRef=useRef(result);resultRef.current=result;
 const sequence=useRef(0);const lock=useRef(false);const stageRef=useRef(stage);stageRef.current=stage;const mainRef=useRef<HTMLElement>(null);const idempotency=useRef<{key:string;signature:string}|null>(null);
 const reset=useCallback((next:Stage="home")=>{sequence.current++;lock.current=false;setBusy(false);setReading(null);setResult(null);setText("");setFeedback({});setError("");setStage(next);history.replaceState({},"","/");},[]);
 const fail=useCallback((e:unknown)=>{if(e instanceof RequestError&&(e.status===404||e.status===410)){reset("expired")}else setError(message(e))},[reset]);
 useEffect(()=>{setFavorites(getFavorites());const update=()=>setFavorites(getFavorites());window.addEventListener("storage",update);return()=>window.removeEventListener("storage",update)},[]);
 useEffect(()=>{const id=new URLSearchParams(location.search).get("reading");if(!id)return;let stopped=false;setBusy(true);api<Reading>(`/api/readings/${encodeURIComponent(id)}`).then(r=>{if(stopped)return;setReading(r);if(r.reveals?.length){setResult(r.reveals[0]);setStage("opened")}else setStage("ready");setFeedback(Object.fromEntries((r.feedback||[]).map((f:{quote_id:string;fit:string;reason:string|null})=>[f.quote_id,{fit:f.fit,reason:f.reason}])))}).catch(e=>{if(!stopped)fail(e)}).finally(()=>{if(!stopped)setBusy(false)});return()=>{stopped=true}},[fail]);
 useEffect(()=>{if(!reading)return;const expire=()=>{if(Date.now()>=reading.expires_at){reset("expired");return true}return false};const timer=window.setTimeout(expire,Math.max(0,reading.expires_at-Date.now()));const visible=()=>{if(document.visibilityState!=="visible"||expire())return;const seq=sequence.current;api<Reading>(`/api/readings/${reading.id}`).then(r=>{if(seq!==sequence.current)return;setReading(r);const old=resultRef.current;const next=old?r.reveals?.find((v:Result)=>v.slot===old.slot)||null:null;setResult(next);if(old&&!next&&stageRef.current==="opened"){setStage("ready");toast("这段原文暂时撤下，可以看看其他书签。")}}).catch(e=>{if(seq===sequence.current&&e instanceof RequestError&&e.status===404)reset("expired")})};document.addEventListener("visibilitychange",visible);return()=>{clearTimeout(timer);document.removeEventListener("visibilitychange",visible)}},[reading?.id,reading?.expires_at,reset]);
 useEffect(()=>{if(stage!=="home")mainRef.current?.focus({preventScroll:true})},[stage]);
 const loadCollection=useCallback(async()=>{setCollectionBusy(true);setCollectionError("");try{const ids=getFavorites();setFavorites(ids);const data=await api<{quotes:Quote[]}>(`/api/quotes?ids=${ids.join(",")}`);setSavedQuotes(data.quotes);if(data.quotes.length!==ids.length)toast("部分原文已撤下，暂不展示。")}catch(e){setCollectionError(message(e))}finally{setCollectionBusy(false)}},[]);
 const showCollection=()=>{setError("");setStage("collection");void loadCollection()};
 const start=useCallback(async(topic?:Topic)=>{if(lock.current)return null;if(!topic&&!text.trim()){setError("写下一句话，或者选择下面的情境。");document.getElementById("concern")?.focus();return null}lock.current=true;setBusy(true);setError("");const seq=++sequence.current;const value=topic?"":text.trim();const signature=JSON.stringify([value,topic,mode]);if(idempotency.current?.signature!==signature)idempotency.current={signature,key:crypto.randomUUID()};try{const r=await api<Reading&{status:string}>("/api/readings","POST",{text:value,topic,preference:mode,request_key:idempotency.current!.key});if(sequence.current!==seq)return null;setText("");setResult(null);setFeedback({});idempotency.current=null;if(r.status==="support"||r.status==="fallback"){setReading(null);history.replaceState({},"","/");setStage(r.status);return {status:r.status}}setReading(r);setStage("ready");history.replaceState({},"",`/?reading=${r.id}`);return {status:"ready",bookmarks:r.bookmarks.map((b:{id:string})=>b.id)}}catch(e){if(sequence.current===seq)setError(message(e));return null}finally{if(sequence.current===seq){lock.current=false;setBusy(false)}}},[text,mode]);
 const reveal=useCallback(async(slot:string)=>{if(!reading||lock.current)return null;lock.current=true;setBusy(true);setError("");const seq=++sequence.current;try{const r=await api<Result>(`/api/readings/${reading.id}/reveal`,"POST",{bookmark_id:slot});if(sequence.current!==seq)return null;setResult(r);setStage("opened");return {quote_id:r.quote.id,origin:r.guidance.origin}}catch(e){if(sequence.current===seq)fail(e);return null}finally{if(sequence.current===seq){lock.current=false;setBusy(false)}}},[reading,fail]);
 const clear=async()=>{if(lock.current)return;lock.current=true;setBusy(true);setError("");try{if(reading)await api(`/api/readings/${reading.id}`,"DELETE",{});reset();toast("本次阅读已清除，收藏的原文会保留。")}catch(e){if(e instanceof RequestError&&e.status===404){reset();toast("本次阅读已失效。")}else{setError(message(e));lock.current=false;setBusy(false)}}};
 const toggleSave=(q:Quote)=>{try{const current=getFavorites();const next=current.includes(q.id)?current.filter(id=>id!==q.id):[q.id,...current];localStorage.setItem(STORE,JSON.stringify(next));setFavorites(next);setSavedQuotes(old=>old.filter(v=>next.includes(v.id)));toast(next.includes(q.id)?"这一句已留在本机，未保存你的心事。":"已移除这枚书签。")}catch{toast.error("浏览器暂时无法保存。请检查本机存储设置后重试。")}};
 const sendFeedback=async(fit:string,reason:string|null=null)=>{if(!reading||!result||feedbackBusy)return;setFeedbackBusy(true);const rid=reading.id,qid=result.quote.id,seq=sequence.current;try{await api(`/api/readings/${rid}/feedback`,"POST",{bookmark_id:result.slot,fit,reason});if(seq===sequence.current)setFeedback(old=>({...old,[qid]:{fit,reason}}))}catch(e){if(seq===sequence.current)toast.error(message(e))}finally{setFeedbackBusy(false)}};
 const actions=useRef({start,reveal});actions.current={start,reveal};
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const tool={name:"start_situation_reading",title:"按情境翻书",description:"选择预设情境，创建私密短期阅读并在页面展示可选书签。不会揭晓原文。",inputSchema:{type:"object",properties:{topic:{type:"string",enum:["start","rest","read"]}},required:["topic"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(input:unknown){if(!input||typeof input!=="object"||Object.keys(input).length!==1||!['start','rest','read'].includes((input as {topic:string}).topic))throw new Error("topic must be start, rest, or read");const r=await actions.current.start((input as {topic:Topic}).topic);if(!r)throw new Error("Reading could not be created");return r}};try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort()},[]);
 const currentFeedback=result?feedback[result.quote.id]:null;const homeStage=stage==="home";
 return <div className="site-shell"><a href="#main" className="skip-link">跳到主要内容</a><Toaster theme="light" position="bottom-center" richColors/>
 <header className="site-header"><a className="brand" href="/" onClick={e=>{e.preventDefault();if(!busy)setStage(reading?"ready":"home")}}><span className="brand-mark"><BookOpen size={21}/></span><span>情境书签<small>A PAGE FOR NOW</small></span></a><nav aria-label="主导航"><button disabled={busy} className={stage!=="collection"?"nav-active":""} onClick={()=>setStage(reading?(result?"opened":"ready"):"home")}>翻一页</button><button disabled={busy} className={stage==="collection"?"nav-active collection-link":"collection-link"} onClick={showCollection}><Bookmark size={16}/>我的书签{favorites.length>0&&<span className="collection-count">{favorites.length}</span>}</button></nav><span className="header-note">留一点时间，给自己。</span></header>
 <main id="main" ref={mainRef} tabIndex={-1}><div className="above-book"><span>心事有处安放，文字自有回响。</span><span className="edition">第一辑 · 与此刻相遇</span></div>
 {reading&&stage!=="collection"&&<div className="back-line"><button className="subtle-button" disabled={busy} onClick={()=>{setStage("ready");setError("")}}><ArrowLeft size={15}/>回到书签</button><button className="subtle-button clear-link" disabled={busy} onClick={clear}><Trash2 size={14}/>清除本次阅读</button></div>}
 {error&&!homeStage&&<p className="error-message" role="alert">{error}</p>}
 {homeStage&&<div className="book-shell"><Cover/><section className="writing-panel"><div className="page-top"><span>写 给 现 在 的 你</span><span>01 — 03</span></div><div className="writing-content"><span className="section-kicker"><Feather size={17}/>从这里开始</span><h2>有什么事，<br className="mobile-break"/>想暂时放在这里？</h2><p className="subtext">烦恼、期待，或一句还没想好的话，都可以。</p><form onSubmit={e=>{e.preventDefault();void start()}}><label className="sr-only" htmlFor="concern">此刻的心事</label><div className="text-paper"><textarea id="concern" placeholder="最近，我……" maxLength={500} value={text} disabled={busy} onChange={e=>setText(e.target.value)} aria-describedby="input-note"/><div className="textarea-bottom" id="input-note"><span>不用组织语言，想到什么就写什么。</span><span>{text.length} / 500</span></div></div><fieldset className="support-choice" disabled={busy}><legend>这一刻，我更需要 <span>（选填）</span></legend><RadioGroup value={mode} onValueChange={v=>setMode(v as Preference)} aria-label="支持方式"><label><RadioGroupItem value="comfort" aria-label="先安慰我"/>先安慰我</label><label><RadioGroupItem value="clarity" aria-label="帮我理清"/>帮我理清</label><label><RadioGroupItem value="action" aria-label="给我一点动力"/>给我一点动力</label></RadioGroup></fieldset>{error&&<p className="error-message" role="alert">{error}</p>}<button className="primary-button" disabled={busy} type="submit">{busy?<><LoaderCircle size={18} className="spin"/>正在准备书签</>:<>去翻一页<ArrowRight size={19}/></>}</button></form><p className="privacy-note">心事不会公开，也不保存你的输入。<button className="inline-link" onClick={()=>setDialog("privacy")}>隐私说明</button></p><div className="or-divider"><span>不想写，也没关系</span></div><div className="situation-links"><button disabled={busy} onClick={()=>start("start")}><Sparkles size={17}/><span>想开始，有点不敢</span><ArrowUpRight size={15}/></button><button disabled={busy} onClick={()=>start("rest")}><Leaf size={17}/><span>有点累，想歇一会儿</span><ArrowUpRight size={15}/></button></div><button disabled={busy} className="just-read" onClick={()=>start("read")}>没什么特别的，只想读一句<ArrowRight size={14}/></button></div><div className="page-bottom"><span>把心事轻轻放下</span><span>— 01 —</span></div></section></div>}
 {stage==="ready"&&reading&&<div className="book-shell"><Cover/><section className="writing-panel"><div className="page-top"><span>与 一 页 文 字 相 遇</span><span>02 — 03</span></div><div className="reading-stage"><span className="stage-number">CHOOSE YOUR PAGE</span><h2 className="stage-heading">挑一枚，随心就好。</h2><p className="stage-description">不用猜哪一枚更好。<br/>每枚书签，都藏着一段不同的文字。</p><div className="ribbon-group">{reading.bookmarks.map((b,i)=>{const Icon=[Leaf,Wind,Sun][i];return <button className="ribbon" key={b.id} disabled={busy||!b.available} aria-label={`打开第${b.id}枚书签`} onClick={()=>reveal(b.id)}><Icon size={25} strokeWidth={1}/><span className="ribbon-name">{["一","二","三"][i]}</span><span className="ribbon-index">{b.available?`0${b.id}`:"暂不可用"}</span></button>})}</div>{busy?<div className="loading-message" role="status"><LoaderCircle className="spin" size={17}/>正在翻开这一页</div>:<p className="reading-note">按情境筛选，随机相遇；不预示命运。<br/>当前为项目编辑解读，暂不提供个性化 AI 分析。</p>}<button className="subtle-button stage-small-button" aria-pressed={skipMotion} onClick={()=>setSkipMotion(!skipMotion)}>{skipMotion?<Check size={14}/>:null}{skipMotion?"已关闭翻页动画":"跳过翻页动画"}</button></div><div className="page-bottom"><span>选择没有对错</span><span>— 02 —</span></div></section></div>}
 {stage==="opened"&&result&&<div className={`book-shell read-spread ${skipMotion?"":"page-flip"}`} key={result.slot}><section className="quote-page"><span className="ribbon-tag" aria-hidden="true"/><div className="page-top"><span>一 页 原 文</span><span>第 {result.slot} 枚书签</span></div><div className="quote-center"><span className="quote-ornament"><Leaf size={27} strokeWidth={1}/></span><blockquote>{result.quote.text}</blockquote><div className="quote-author">〔{result.quote.era}〕{result.quote.author}</div><div className="quote-work">《{result.quote.work}》</div><Source q={result.quote}/></div><div className="page-bottom"><span>文字有来处</span><span>— 03 —</span></div></section><section className="writing-panel guidance-page"><div className="page-top"><span>把 这 一 页 留 给 自 己</span><span>READ SLOWLY</span></div><div className="guidance-body"><span className="origin-badge">项目编辑解读 · 非个性化生成</span><h2>读到这里，慢一点。</h2><p className="guidance-text">{result.guidance.interpretation}</p>{result.guidance.small_action&&<div className="action-box"><h3><Feather size={16}/>可以试的一小步</h3><p>{result.guidance.small_action}</p><small>愿意就试试，不做也没关系。</small></div>}<div className="reading-actions"><button className={`save-button ${favorites.includes(result.quote.id)?"saved":""}`} onClick={()=>toggleSave(result.quote)}>{favorites.includes(result.quote.id)?<BookmarkCheck size={17}/>:<Bookmark size={17}/>} {favorites.includes(result.quote.id)?"已保存这句":"保存这句"}</button><button className="subtle-button" onClick={()=>{setStage("ready");setError("")}}>看看另一页<ArrowRight size={15}/></button></div><div className="feedback-row"><div><span>这页对你来说……</span><button disabled={feedbackBusy} className={`feedback-button ${currentFeedback?.fit==="fit"?"active":""}`} onClick={()=>sendFeedback("fit")}><ThumbsUp size={14}/>贴合</button><button disabled={feedbackBusy} className={`feedback-button ${currentFeedback?.fit==="not_fit"?"active":""}`} onClick={()=>sendFeedback("not_fit")}><MessageCircle size={14}/>不太贴合</button></div>{currentFeedback?.fit==="not_fit"&&<div className="feedback-reasons">{Object.entries(reasonLabels).map(([key,label])=><button className={currentFeedback.reason===key?"active":""} disabled={feedbackBusy} key={key} onClick={()=>sendFeedback("not_fit",key)}>{label}</button>)}</div>}{currentFeedback&&<p className="thanks" role="status">谢谢你，这能帮助我们把文字选得更贴切。</p>}</div></div><div className="page-bottom"><span>不必急着找到答案</span><span>— 04 —</span></div></section></div>}
 {stage==="collection"&&<section className="collection-page"><div className="collection-header"><div><h1>留下的句子</h1><p>有些文字，值得在另一个日子重逢。<br/>仅保存在这台设备的浏览器里，不包含你的心事。</p></div><button className="subtle-button" onClick={()=>setStage(reading?(result?"opened":"ready"):"home")}><ArrowLeft size={15}/>回去翻一页</button></div>{collectionBusy?<div className="loading-message" role="status"><LoaderCircle size={18} className="spin"/>正在取出书签</div>:collectionError?<div className="empty-collection"><p role="alert">{collectionError}</p><button className="save-button" onClick={loadCollection}>再试一次</button></div>:savedQuotes.length?<div className="saved-grid">{savedQuotes.map(q=><article className="saved-card" key={q.id}><Bookmark size={17} strokeWidth={1}/><blockquote>{q.text}</blockquote><p>{q.author} ·《{q.work}》</p><div className="saved-card-footer"><button onClick={()=>setDetail(q)}>再读一遍<ArrowUpRight size={13}/></button><button aria-label={`移除《${q.work}》这枚书签`} onClick={()=>toggleSave(q)}><Trash2 size={14}/>移除</button></div></article>)}</div>:<div className="empty-collection"><Bookmark size={39} strokeWidth={1}/><h2>书签夹里，还留着空白。</h2><p>读到喜欢的文字时，点一下“保存这句”。<br/>它就会在这里等你。</p><button className="primary-button" onClick={()=>setStage(reading?"ready":"home")}>去遇见一句<ArrowRight size={17}/></button></div>}</section>}
 {(stage==="support"||stage==="expired"||stage==="fallback")&&<section className="collection-page"><div className="support-screen">{stage==="support"?<><Heart size={30} strokeWidth={1}/><h1>先把这一刻，留给你的安全。</h1><p>如果你现在正处在危险中，或担心自己会伤害自己或他人，请先联系当地紧急服务，或找一位可信的人来到你身边。</p><p>尽量与可能造成伤害的物品拉开距离，去一个有人、相对安全的地方。你不必独自撑过这一刻。</p><p>这里无法判断你的完整处境，也不能提供紧急救援。如果你只是想表达难过，也可以先与信任的人聊一聊。</p></>:stage==="expired"?<><BookOpen size={30} strokeWidth={1}/><h1>这一页，已经合上了。</h1><p>本次阅读已失效或无法访问。为了保护隐私，阅读会话在 30 分钟后停止访问；你保存到本机的原文仍在“我的书签”里。</p></>:<><Leaf size={30} strokeWidth={1}/><h1>还没有找到足够贴合的原文。</h1><p>不必为此勉强找到一个答案。你可以先歇一会儿，或者重新选择一个情境。此刻的感受不需要由一句名言来证明。</p></>}<button className="primary-button" onClick={()=>reset()}>回到首页<ArrowRight size={17}/></button></div></section>}
 <div className="below-book" aria-label="阅读步骤"><span><span className="step">01</span>放下心事</span><i/><span><span className="step">02</span>选枚书签</span><i/><span><span className="step">03</span>读一页文字</span></div></main>
 <footer><span>文字供日常启发，不替你决定人生。</span><div><button onClick={()=>setDialog("about")}>关于这本书</button><button onClick={()=>setDialog("privacy")}>隐私说明</button></div></footer>
 <Dialog open={dialog!==null} onOpenChange={open=>{if(!open)setDialog(null)}}><DialogContent className="max-w-[min(620px,calc(100%-32px))] p-8"><DialogTitle className="font-normal text-2xl">{dialog==="privacy"?"让心事，有自己的边界。":"关于情境书签"}</DialogTitle><DialogDescription>{dialog==="privacy"?"当前文学阅读版本 · 2026 年 9 月 12 日":"一页原文，一段陪伴，一点新的可能。"}</DialogDescription><div className="dialog-prose">{dialog==="privacy"?<><h3>你的输入</h3><p>输入会发送到本站服务器，用于简单情境匹配与安全提示。当前版本不调用外部模型，也不把输入原文写入数据库。请避免输入姓名、电话等个人信息。</p><h3>短期阅读与反馈</h3><p>服务器保留情境类别、书签绑定和选项反馈。会话 30 分钟后不可访问，到期数据会在后续接口访问时清理；点击“清除本次阅读”可立即删除该会话与关联反馈。未配置独立定时清理任务。</p><h3>本机收藏</h3><p>“保存这句”只在本机保存原文编号，不保存心事和解读。清除浏览器网站数据或换设备后，收藏不会同步。可在“我的书签”逐条移除。</p><h3>运行与访问</h3><p>本站使用 Sites 托管及 Cloudflare 数据存储。匿名凭证用于保护会话；基础限流使用短期网络地址摘要。应用不主动记录输入正文或开启会话录屏，托管服务的运行日志与备份按其政策处理。阅读页到期不等于所有基础设施数据同时消失。</p></>:<><p>情境书签希望让真实的文学文字，成为日常的一小段停留。你可以写下心事，也可以什么都不解释，直接翻开一页。</p><h3>文字从哪里来</h3><p>第一辑收入 30 段古典原文节选。每页都附作者、作品、可核对的来源和必要异文说明；简体字及换行用于阅读。</p><h3>如何理解这些解读</h3><p>当前是文学阅读试用版。解读由项目预先编写，不是作者原话，也不是对你个人的心理分析。情境匹配采用简单规则，未接入个性化 AI。你可以不同意解读，或只读原文。</p><p>书签已根据情境筛选，再随机排列。不预测未来，不提供心理诊断、治疗或紧急救援。</p></>}</div></DialogContent></Dialog>
 <Dialog open={!!detail} onOpenChange={open=>{if(!open)setDetail(null)}}><DialogContent className="max-w-[min(620px,calc(100%-32px))] p-8"><DialogTitle className="font-normal text-xl">{detail?.work||"原文"}</DialogTitle><DialogDescription>{detail?.author}</DialogDescription>{detail&&<div className="dialog-prose"><blockquote>{detail.text}</blockquote><span className="origin-badge">项目编辑解读</span><p>{detail.note}</p><Source q={detail}/></div>}</DialogContent></Dialog>
 </div>
}
