"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { ArrowUpRight, ArrowRight, ArrowLeft, Bookmark, BookmarkCheck, BookOpen, Feather, Leaf, Sparkles, Sun, Wind, Heart, HomeIcon, LoaderCircle, Trash2, Check, ThumbsUp, MessageCircle, ExternalLink, Info, ShieldCheck, Moon, ChevronRight } from "lucide-react";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Toaster } from "@/components/ui/sonner";
import ReadingLibrary, {type LibraryView} from "@/components/reading-library";
import BackgroundMusic from "@/components/background-music";
import { toast } from "sonner";
import type { Quote, Topic, Preference } from "@/content/quotes";
type Result={slot:string;quote:Quote;guidance:{origin:"editorial"|"ai";interpretation:string;small_action:string|null}};
type Reading={id:string;origin:"editorial"|"ai";topic:Topic;preference:Preference;bookmarks:{id:string;available:boolean;origin?:"ai"|"editorial"}[];expires_at:number;reveals?:Result[];feedback?:{quote_id:string;fit:string;reason:string|null}[]};
type Stage="home"|"ready"|"opened"|"support"|"expired"|"collection"|"fallback"|LibraryView;
const STORE="situation-bookmarks:quotes:v1";
const reasonLabels={situation:"不符合我的情况",pressure:"建议有压力",unclear:"不太看得懂",source:"想核实出处"};
class RequestError extends Error{constructor(public status:number,message:string){super(message)}}
async function api<T=Record<string,unknown>>(path:string,method="GET",data?:unknown){const response=await fetch(path,{method,headers:method!=="GET"?{"Content-Type":"application/json"}:undefined,body:data===undefined?undefined:JSON.stringify(data),cache:"no-store",signal:AbortSignal.timeout(path==="/api/readings"&&method==="POST"?55000:12000)});const result=await response.json().catch(()=>({error:"这次没能读到书页，请重试。"}));if(!response.ok)throw new RequestError(response.status,(result as {error?:string}).error||"这次没能读到书页，请重试。");return result as T}
function getFavorites():string[]{try{const v=JSON.parse(localStorage.getItem(STORE)||"[]");return Array.isArray(v)?[...new Set(v.filter((x:unknown)=>typeof x==="string"&&/^q\d{3,4}$/.test(x as string)))].slice(0,1000) as string[]:[]}catch{return []}}
function message(e:unknown){return e instanceof RequestError?e.message:"连接暂时中断了，请再试一次。"}
function Cover(){return <aside className="art-panel" aria-label="安静的阅读时光"><img className="reading-art" src="/cozy-reading.webp" alt="月光下，一位读者坐在花树旁安静地读书" width="800" height="1200"/><div className="art-caption"><span>A LITTLE SPACE FOR YOU</span><p>在文字里，<br/>遇见此刻的自己。</p></div></aside>}
function Source({q}:{q:Quote}){const sourceNote=q.annotationKind==='source-note';return <details className="quote-source"><summary>{sourceNote?'出处与阅读说明':q.fullText?'出处与原作上下文':'原文出处与白话含义'}</summary>{q.fullText?<><p className="source-fulltext">{q.fullText}</p><p>作品导读说明整首作品，不等于逐句译文。</p></>:<p>{q.meaning}</p>}<p>{q.location}。{q.sourceKind==='gutenberg'?'保留英文原文展示。':'页面采用简体字展示。'}</p><a href={q.source} target="_blank" rel="noopener noreferrer">查看来源 <ExternalLink size={12}/></a><p>{q.sourceKind==='corpus'?'语料记录核对':'来源记录核对'}：{q.verifiedAt}</p>{q.sourceKind==='corpus'&&<a href="/NOTICE-chinese-poetry.txt" target="_blank" rel="noopener noreferrer">chinese-poetry · MIT 语料许可</a>}</details>}
export default function Home(){
 const [stage,setStage]=useState<Stage>("home");const [text,setText]=useState("");const [mode,setMode]=useState<Preference>("auto");const [reading,setReading]=useState<Reading|null>(null);const [result,setResult]=useState<Result|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [favorites,setFavorites]=useState<string[]>([]);const [savedQuotes,setSavedQuotes]=useState<Quote[]>([]);const [collectionBusy,setCollectionBusy]=useState(false);const [collectionError,setCollectionError]=useState("");const [dialog,setDialog]=useState<"about"|"privacy"|null>(null);const [detail,setDetail]=useState<Quote|null>(null);const [feedback,setFeedback]=useState<Record<string,{fit:string;reason:string|null}>>({});const [feedbackBusy,setFeedbackBusy]=useState(false);const [skipMotion,setSkipMotion]=useState(false);
 const [bookmarkGroup,setBookmarkGroup]=useState(0);
 const [noteQuote,setNoteQuote]=useState<Quote|null>(null); const libraryStage=["shelf","daily","notes"].includes(stage); const writeNote=(q:Quote)=>{setNoteQuote({...q});setStage("notes")};
 const resultRef=useRef(result);resultRef.current=result;
 const sequence=useRef(0);const lock=useRef(false);const stageRef=useRef(stage);stageRef.current=stage;const mainRef=useRef<HTMLElement>(null);const idempotency=useRef<{key:string;signature:string}|null>(null);
 const reset=useCallback((next:Stage="home")=>{sequence.current++;lock.current=false;setBusy(false);setReading(null);setResult(null);setText("");setFeedback({});setError("");setStage(next);history.replaceState({},"","/");},[]);
 const fail=useCallback((e:unknown)=>{if(e instanceof RequestError&&(e.status===404||e.status===410)){reset("expired")}else setError(message(e))},[reset]);
 useEffect(()=>{setFavorites(getFavorites());const update=()=>setFavorites(getFavorites());window.addEventListener("storage",update);return()=>window.removeEventListener("storage",update)},[]);
 useEffect(()=>{const id=new URLSearchParams(location.search).get("reading");if(!id)return;let stopped=false;setBusy(true);api<Reading>(`/api/readings/${encodeURIComponent(id)}`).then(r=>{if(stopped)return;setReading(r);if(r.reveals?.length){setResult(r.reveals[0]);setStage("opened")}else setStage("ready");setFeedback(Object.fromEntries((r.feedback||[]).map((f:{quote_id:string;fit:string;reason:string|null})=>[f.quote_id,{fit:f.fit,reason:f.reason}])))}).catch(e=>{if(!stopped)fail(e)}).finally(()=>{if(!stopped)setBusy(false)});return()=>{stopped=true}},[fail]);
 useEffect(()=>{if(!reading)return;const expire=()=>{if(Date.now()>=reading.expires_at){reset("expired");return true}return false};const timer=window.setTimeout(expire,Math.max(0,reading.expires_at-Date.now()));const visible=()=>{if(document.visibilityState!=="visible"||expire())return;const seq=sequence.current;api<Reading>(`/api/readings/${reading.id}`).then(r=>{if(seq!==sequence.current)return;setReading(r);const old=resultRef.current;const next=old?r.reveals?.find((v:Result)=>v.slot===old.slot)||null:null;setResult(next);if(old&&!next&&stageRef.current==="opened"){setStage("ready");toast("这段原文暂时撤下，可以看看其他书签。")}}).catch(e=>{if(seq===sequence.current&&e instanceof RequestError&&e.status===404)reset("expired")})};document.addEventListener("visibilitychange",visible);return()=>{clearTimeout(timer);document.removeEventListener("visibilitychange",visible)}},[reading?.id,reading?.expires_at,reset]);
 useEffect(()=>{if(stage!=="home")mainRef.current?.focus({preventScroll:true})},[stage]);
 const loadCollection=useCallback(async()=>{setCollectionBusy(true);setCollectionError("");try{const ids=getFavorites();setFavorites(ids);const data=await api<{quotes:Quote[]}>(`/api/quotes?ids=${ids.join(",")}`);setSavedQuotes(data.quotes);if(data.quotes.length!==ids.length)toast("部分原文已撤下，暂不展示。")}catch(e){setCollectionError(message(e))}finally{setCollectionBusy(false)}},[]);
 const showCollection=()=>{setError("");setStage("collection");void loadCollection()};
 const start=useCallback(async(topic?:Topic)=>{if(lock.current)return null;if(!topic&&!text.trim()){setError("写下一句话，或者选择下面的情境。");document.getElementById("concern")?.focus();return null}lock.current=true;setBusy(true);setError("");const seq=++sequence.current;const value=topic?"":text.trim();const signature=JSON.stringify([value,topic,mode]);if(idempotency.current?.signature!==signature)idempotency.current={signature,key:crypto.randomUUID()};try{const r=await api<Reading&{status:string}>("/api/readings","POST",{text:value,topic,preference:mode,request_key:idempotency.current!.key});if(sequence.current!==seq)return null;setText("");setResult(null);setFeedback({});idempotency.current=null;if(r.status==="support"||r.status==="fallback"){setReading(null);history.replaceState({},"","/");setStage(r.status);return {status:r.status}}setReading(r);setBookmarkGroup(0);setStage("ready");history.replaceState({},"",`/?reading=${r.id}`);return {status:"ready",bookmarks:r.bookmarks.map((b:{id:string})=>b.id)}}catch(e){if(sequence.current===seq)setError(message(e));return null}finally{if(sequence.current===seq){lock.current=false;setBusy(false)}}},[text,mode]);
 const reveal=useCallback(async(slot:string)=>{if(!reading||lock.current)return null;lock.current=true;setBusy(true);setError("");const seq=++sequence.current;try{const r=await api<Result>(`/api/readings/${reading.id}/reveal`,"POST",{bookmark_id:slot});if(sequence.current!==seq)return null;setResult(r);setStage("opened");return {quote_id:r.quote.id,origin:r.guidance.origin}}catch(e){if(sequence.current===seq)fail(e);return null}finally{if(sequence.current===seq){lock.current=false;setBusy(false)}}},[reading,fail]);
 const clear=async()=>{if(lock.current)return;lock.current=true;setBusy(true);setError("");try{if(reading)await api(`/api/readings/${reading.id}`,"DELETE",{});reset();toast("本次阅读已清除，收藏的原文会保留。")}catch(e){if(e instanceof RequestError&&e.status===404){reset();toast("本次阅读已失效。")}else{setError(message(e));lock.current=false;setBusy(false)}}};
 const toggleSave=(q:Quote)=>{try{const current=getFavorites();const next=current.includes(q.id)?current.filter(id=>id!==q.id):[q.id,...current];localStorage.setItem(STORE,JSON.stringify(next));setFavorites(next);setSavedQuotes(old=>old.filter(v=>next.includes(v.id)));toast(next.includes(q.id)?"这一句已留在本机，未保存你的心事。":"已移除这枚书签。")}catch{toast.error("浏览器暂时无法保存。请检查本机存储设置后重试。")}};
 const sendFeedback=async(fit:string,reason:string|null=null)=>{if(!reading||!result||feedbackBusy)return;setFeedbackBusy(true);const rid=reading.id,qid=result.quote.id,seq=sequence.current;try{await api(`/api/readings/${rid}/feedback`,"POST",{bookmark_id:result.slot,fit,reason});if(seq===sequence.current)setFeedback(old=>({...old,[qid]:{fit,reason}}))}catch(e){if(seq===sequence.current)toast.error(message(e))}finally{setFeedbackBusy(false)}};
 const actions=useRef({start,reveal});actions.current={start,reveal};
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const tool={name:"start_situation_reading",title:"按情境翻书",description:"选择预设情境，创建短期阅读并展示可选书签。start/rest 会将预设情境发送给知乎直答生成解读，read 使用编辑解读。不会揭晓原文。",inputSchema:{type:"object",properties:{topic:{type:"string",enum:["start","rest","read"]}},required:["topic"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(input:unknown){if(!input||typeof input!=="object"||Object.keys(input).length!==1||!['start','rest','read'].includes((input as {topic:string}).topic))throw new Error("topic must be start, rest, or read");const r=await actions.current.start((input as {topic:Topic}).topic);if(!r)throw new Error("Reading could not be created");return r}};try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort()},[]);
 const currentFeedback=result?feedback[result.quote.id]:null;const homeStage=stage==="home";
 return <div className="site-shell">
 <a href="#main" className="skip-link">跳到主要内容</a><Toaster theme="light" position="bottom-center" richColors/>
 <header className="site-header">
  <a className="brand" href="/" onClick={e=>{e.preventDefault();if(!busy)setStage(reading?"ready":"home")}}><span className="brand-mark"><BookOpen size={26} strokeWidth={1.7}/></span><span>情境书签<small>A PAGE FOR NOW</small></span></a>
  <div className="sidebar-welcome"><span className="welcome-icon"><Moon size={21} strokeWidth={1.4}/></span><p>欢迎来到<br/><strong>你的阅读角落</strong></p></div>
  <nav aria-label="主导航">
   <button disabled={busy} className={(stage!=="collection"&&!libraryStage)?"nav-active":""} aria-current={(stage!=="collection"&&!libraryStage)?"page":undefined} onClick={()=>setStage(reading?(result?"opened":"ready"):"home")}><BookOpen size={19}/>翻一页<ChevronRight className="nav-chevron" size={15}/></button>
   <button disabled={busy} className={stage==="collection"?"nav-active collection-link":"collection-link"} aria-current={stage==="collection"?"page":undefined} onClick={showCollection}><Bookmark size={19}/>我的书签<span className="collection-count">{favorites.length}</span></button>
   <button disabled={busy} className={stage==="shelf"?"nav-active":""} aria-current={stage==="shelf"?"page":undefined} onClick={()=>setStage("shelf")}><Heart size={19}/>心情书架</button>
   <button disabled={busy} className={stage==="daily"?"nav-active":""} aria-current={stage==="daily"?"page":undefined} onClick={()=>setStage("daily")}><Sun size={19}/>每日一页</button>
   <button disabled={busy} className={stage==="notes"?"nav-active":""} aria-current={stage==="notes"?"page":undefined} onClick={()=>setStage("notes")}><Feather size={19}/>我的随记</button>
  </nav>
  <div className="sidebar-bottom"><p>留一点时间，<br/>给自己。</p><div className="sidebar-links"><button onClick={()=>setDialog("about")}><Info size={17}/>关于这本书</button><button onClick={()=>setDialog("privacy")}><ShieldCheck size={17}/>隐私说明</button></div><span className="sidebar-edition">第一辑 · 与此刻相遇</span></div>
 </header>
 <main id="main" ref={mainRef} tabIndex={-1}>
  <div className="workspace-header"><span><Feather size={17} strokeWidth={1.5}/>一页文字，一点陪伴</span><div className="workspace-actions"><BackgroundMusic/><button className="quiet-link" disabled={busy} onClick={()=>setDialog("privacy")}><ShieldCheck size={15}/>心事不会公开</button></div></div>
  {reading&&stage!=="collection"&&!libraryStage&&<div className="back-line"><div className="back-actions"><button className="subtle-button" disabled={busy} onClick={()=>reset()}><HomeIcon size={15}/>返回首页</button>{stage==="opened"&&<button className="subtle-button" disabled={busy} onClick={()=>{setStage("ready");setError("")}}><ArrowLeft size={15}/>回到书签</button>}</div><button className="subtle-button clear-link" disabled={busy} onClick={clear}><Trash2 size={14}/>清除本次阅读</button></div>}
  {error&&!homeStage&&<p className="error-message" role="alert">{error}</p>}
  {homeStage&&<>
   <div className="page-heading"><div><span className="section-kicker">YOUR QUIET MOMENT</span><h1>此刻，翻一页。</h1><p>让一句文字，陪你停留片刻。</p></div><span className="heading-flower" aria-hidden="true"><Sparkles size={31} strokeWidth={1}/></span></div>
   <div className="home-spread">
    <section className="writing-panel"><div className="page-top"><span><Feather size={16}/>写给现在的你</span><span>01 / 03</span></div><div className="writing-content"><h2>有什么事，想放在这里？</h2><p className="subtext">烦恼、期待，或一句还没想好的话，都可以。</p>
     <form onSubmit={e=>{e.preventDefault();void start()}}><label className="sr-only" htmlFor="concern">此刻的心事</label><div className="text-paper"><textarea id="concern" placeholder="最近，我……" maxLength={500} value={text} disabled={busy} onChange={e=>setText(e.target.value)} aria-describedby="input-note"/><div className="textarea-bottom" id="input-note"><span>想到什么，就写什么。</span><span>{text.length} / 500</span></div></div>
      <fieldset className="support-choice" disabled={busy}><legend>这一刻，我更需要 <span>选填</span></legend><RadioGroup value={mode} onValueChange={v=>setMode(v as Preference)} aria-label="支持方式"><label><RadioGroupItem value="comfort" aria-label="先安慰我"/>先安慰我</label><label><RadioGroupItem value="clarity" aria-label="帮我理清"/>帮我理清</label><label><RadioGroupItem value="action" aria-label="给我一点动力"/>给我一点动力</label></RadioGroup></fieldset>
      {error&&<p className="error-message" role="alert">{error}</p>}<button className="primary-button" disabled={busy} type="submit">{busy?<><LoaderCircle size={18} className="spin"/>正在为你挑选书签</>:<>去翻一页<ArrowRight size={19}/></>}</button>
     </form><p className="privacy-note">提交后由知乎直答理解你的输入。<button className="inline-link" onClick={()=>setDialog("privacy")}>了解隐私</button></p>
    </div></section><Cover/>
   </div>
   <section className="situation-section" aria-labelledby="situation-heading"><div className="section-line"><h2 id="situation-heading">不想写，也没关系。</h2><span>从一种心情开始</span></div><div className="situation-links">
    <button className="situation-card" disabled={busy} onClick={()=>start("start")}><span className="situation-icon"><Sparkles size={21} strokeWidth={1.4}/></span><span><strong>想开始，有点不敢</strong><small>给新的可能，留一点空间</small></span><ArrowUpRight size={18}/></button>
    <button className="situation-card" disabled={busy} onClick={()=>start("rest")}><span className="situation-icon"><Leaf size={21} strokeWidth={1.4}/></span><span><strong>有点累，想歇一会儿</strong><small>暂时放下，也没关系</small></span><ArrowUpRight size={18}/></button>
    <button className="situation-card just-read" disabled={busy} onClick={()=>start("read")}><span className="situation-icon"><BookOpen size={21} strokeWidth={1.4}/></span><span><strong>没什么特别的，只想读一句</strong><small>让文字，带你去远一点的地方</small></span><ArrowUpRight size={18}/></button>
   </div></section>
  </>}
  {stage==="ready"&&reading&&<section className="selection-panel"><div className="page-top"><span><Bookmark size={16}/>与一页文字相遇</span><span>02 / 03</span></div><div className="reading-stage"><span className="section-kicker">A PAGE IS WAITING</span><h1 className="stage-heading">挑一枚，随心就好。</h1><p className="stage-description">本次共 {reading.bookmarks.length} 枚，每组 6 枚，慢慢挑选。</p><div className="ribbon-group">{reading.bookmarks.slice(bookmarkGroup*6,bookmarkGroup*6+6).map((b,i)=>{const Icon=[Leaf,Wind,Sun][i%3];return <button className="ribbon" key={b.id} disabled={busy||!b.available} aria-label={`打开第${b.id}枚书签`} onClick={()=>reveal(b.id)}><span className="ribbon-top"><span>PAGE {b.id.padStart(2,"0")}</span><Bookmark size={18} strokeWidth={1.3}/></span><span className="ribbon-art" aria-hidden="true"><img src="/cozy-reading.webp" alt=""/><Icon size={25} strokeWidth={1.2}/></span><span className="ribbon-bottom"><span className="ribbon-name">第 {b.id} 枚书签</span><ArrowUpRight size={17}/></span><span className="ribbon-index">{b.available?(b.origin==="ai"?"为你推荐 · 个性化解读":"延伸阅读 · 原文赏读"):"这段原文暂不可用"}</span></button>})}</div><div className="bookmark-pagination"><span>第 {bookmarkGroup+1} / {Math.ceil(reading.bookmarks.length/6)} 组</span><button className="save-button" disabled={busy||reading.bookmarks.length<=6} onClick={()=>{setBookmarkGroup(g=>(g+1)%Math.ceil(reading.bookmarks.length/6));setError("")}}>{bookmarkGroup+1>=Math.ceil(reading.bookmarks.length/6)?"回到第一组":"换一组书签"}<ArrowRight size={15}/></button></div>{busy?<div className="loading-message" role="status"><LoaderCircle className="spin" size={17}/>正在翻开这一页</div>:<p className="reading-note">{reading.origin==="ai"?"前几枚为个性化推荐，其余是延伸阅读；换组不调用模型。":"这次只读文学，原文附项目编辑解读。"}</p>}<button className="subtle-button stage-small-button" aria-pressed={skipMotion} onClick={()=>setSkipMotion(!skipMotion)}>{skipMotion?<Check size={14}/>:null}{skipMotion?"已关闭翻页动画":"跳过翻页动画"}</button></div></section>}
  {stage==="opened"&&result&&<div className={`read-spread ${skipMotion?"":"page-flip"}`} key={result.slot}><section className="quote-page"><div className="page-top"><span>一页原文</span><span>第 {result.slot} 枚书签</span></div><div className="quote-center"><span className="quote-ornament"><Leaf size={30} strokeWidth={1.2}/></span><blockquote>{result.quote.text}</blockquote><div className="quote-author">〔{result.quote.era}〕{result.quote.author}</div><div className="quote-work">《{result.quote.work}》</div></div><Source q={result.quote}/><div className="page-bottom"><span>文字有来处</span><BookOpen size={17} strokeWidth={1.3}/></div></section><section className="guidance-page"><div className="page-top"><span>把这一页留给自己</span><span>READ SLOWLY</span></div><div className="guidance-body"><span className="origin-badge">{result.guidance.origin==="ai"?"知乎直答 · 本次生成，可能有偏差":"项目编辑导读 · 非个性化生成"}</span><h1>读到这里，慢一点。</h1><p className="guidance-text">{result.guidance.interpretation}</p>{result.guidance.small_action&&<div className="action-box"><h2><Feather size={16}/>可以试的一小步</h2><p>{result.guidance.small_action}</p><small>愿意就试试，不做也没关系。</small></div>}<div className="reading-actions"><button className={`save-button ${favorites.includes(result.quote.id)?"saved":""}`} onClick={()=>toggleSave(result.quote)}>{favorites.includes(result.quote.id)?<BookmarkCheck size={17}/>:<Bookmark size={17}/>} {favorites.includes(result.quote.id)?"已保存这句":"保存这句"}</button><button className="subtle-button" onClick={()=>{setStage("ready");setError("")}}>看看另一页<ArrowRight size={15}/></button></div><button className="subtle-button" onClick={()=>writeNote(result.quote)}><Feather size={16}/>为这句话写随记</button><div className="feedback-row"><div><span>这页对你来说……</span><button disabled={feedbackBusy} className={`feedback-button ${currentFeedback?.fit==="fit"?"active":""}`} onClick={()=>sendFeedback("fit")}><ThumbsUp size={14}/>贴合</button><button disabled={feedbackBusy} className={`feedback-button ${currentFeedback?.fit==="not_fit"?"active":""}`} onClick={()=>sendFeedback("not_fit")}><MessageCircle size={14}/>不太贴合</button></div>{currentFeedback?.fit==="not_fit"&&<div className="feedback-reasons">{Object.entries(reasonLabels).map(([key,label])=><button className={currentFeedback.reason===key?"active":""} disabled={feedbackBusy} key={key} onClick={()=>sendFeedback("not_fit",key)}>{label}</button>)}</div>}{currentFeedback&&<p className="thanks" role="status">谢谢你，这能帮助我们把文字选得更贴切。</p>}</div></div></section></div>}
  {stage==="collection"&&<section className="collection-page"><div className="collection-header"><div><span className="section-kicker">YOUR LITTLE COLLECTION</span><h1>留下的句子</h1><p>有些文字，值得在另一个日子重逢。</p><span className="collection-local"><ShieldCheck size={14}/>仅保存在本机，不包含你的心事</span></div><button className="subtle-button" onClick={()=>setStage(reading?(result?"opened":"ready"):"home")}><ArrowLeft size={15}/>回去翻一页</button></div>{collectionBusy?<div className="loading-message" role="status"><LoaderCircle size={18} className="spin"/>正在取出书签</div>:collectionError?<div className="empty-collection"><p role="alert">{collectionError}</p><button className="save-button" onClick={loadCollection}>再试一次</button></div>:savedQuotes.length?<div className="saved-grid">{savedQuotes.map((q,i)=><article className="saved-card" key={q.id}><div className="saved-card-top"><span>NO. {String(i+1).padStart(2,"0")}</span><Bookmark size={19} strokeWidth={1.3}/></div><blockquote>{q.text}</blockquote><p>{q.author} ·《{q.work}》</p><div className="saved-card-footer"><button onClick={()=>setDetail(q)}>再读一遍<ArrowUpRight size={15}/></button><button onClick={()=>writeNote(q)}><Feather size={15}/>写随记</button><button aria-label={`移除《${q.work}》这枚书签`} onClick={()=>toggleSave(q)}><Trash2 size={15}/>移除</button></div></article>)}</div>:<div className="empty-collection"><span className="empty-icon"><Bookmark size={36} strokeWidth={1.2}/></span><h2>书签夹里，还留着空白。</h2><p>读到喜欢的文字时，点一下“保存这句”。<br/>它就会在这里等你。</p><button className="primary-button" onClick={()=>setStage(reading?"ready":"home")}>去遇见一句<ArrowRight size={17}/></button></div>}</section>}
  {(stage==="support"||stage==="expired"||stage==="fallback")&&<section className="collection-page"><div className="support-screen">{stage==="support"?<><Heart size={34} strokeWidth={1.3}/><h1>先把这一刻，留给你的安全。</h1><p>如果你现在正处在危险中，或担心自己会伤害自己或他人，请先联系当地紧急服务，或找一位可信的人来到你身边。</p><p>尽量与可能造成伤害的物品拉开距离，去一个有人、相对安全的地方。你不必独自撑过这一刻。</p><p>这里无法判断你的完整处境，也不能提供紧急救援。如果你只是想表达难过，也可以先与信任的人聊一聊。</p></>:stage==="expired"?<><BookOpen size={34} strokeWidth={1.3}/><h1>这一页，已经合上了。</h1><p>本次阅读已失效或无法访问。为了保护隐私，阅读会话在 30 分钟后停止访问；你保存到本机的原文仍在“我的书签”里。</p></>:<><Leaf size={34} strokeWidth={1.3}/><h1>还没有找到足够贴合的原文。</h1><p>不必为此勉强找到一个答案。你可以先歇一会儿，或者重新选择一个情境。此刻的感受不需要由一句名言来证明。</p></>}<button className="primary-button" onClick={()=>reset()}>回到首页<ArrowRight size={17}/></button></div></section>}
  <div hidden={!libraryStage}><ReadingLibrary view={libraryStage?stage as LibraryView:"shelf"} favorites={favorites} onSave={toggleSave} onDetail={setDetail} noteQuote={noteQuote} onNote={writeNote}/></div>
  <footer><span>文字供日常启发，不替你决定人生。</span><span>慢一点，也很好。</span><div className="mobile-footer-links"><button onClick={()=>setDialog("about")}>关于</button><button onClick={()=>setDialog("privacy")}>隐私说明</button></div></footer>
 </main>
 <Dialog open={dialog!==null} onOpenChange={open=>{if(!open)setDialog(null)}}><DialogContent className="reading-dialog max-w-[min(620px,calc(100%-32px))] p-8"><DialogTitle className="font-normal text-2xl">{dialog==="privacy"?"让心事，有自己的边界。":"关于情境书签"}</DialogTitle><DialogDescription>{dialog==="privacy"?"知乎直答接入版 · 2026 年 9 月 12 日":"一页原文，一段陪伴，一点新的可能。"}</DialogDescription><div className="dialog-prose">{dialog==="privacy"?<><h3>你的输入</h3><p>点击“去翻一页”后，输入会经本站服务器发送给知乎直答，用于理解处境、匹配原文与生成解读。本站不把输入原文写入数据库。知乎对请求数据的处理遵循其服务政策；请避免输入姓名、电话等个人信息。直接选择“只想读一句”时不调用模型。</p><h3>短期阅读与反馈</h3><p>服务器保留情境类别、书签绑定和选项反馈；个性化解读可能包含你表达的处境，会加密暂存，供本次阅读与刷新恢复。会话 30 分钟后不可访问，到期数据会在后续接口访问时清理；点击“清除本次阅读”可立即删除该会话与关联反馈。未配置独立定时清理任务。</p><h3>本机收藏</h3><p>“保存这句”只在本机保存原文编号，不保存心事和解读。清除浏览器网站数据或换设备后，收藏不会同步。可在“我的书签”逐条移除。</p><h3>我的随记</h3><p>随记正文加密保存在服务器，不发送给模型。独立的本机匿名凭证用于读取和解密，有效期一年，访问随记时续期；换设备或清除网站数据后无法找回。随记不会随短期阅读到期而删除，可逐条删除或导出文字备份。</p><h3>运行与访问</h3><p>本站使用 Sites 托管及 Cloudflare 数据存储。匿名凭证用于保护会话；基础限流使用短期网络地址摘要。应用不主动记录输入正文或开启会话录屏，托管服务的运行日志与备份按其政策处理。阅读页到期不等于所有基础设施数据同时消失。</p></>:<><p>情境书签希望让真实的文学文字，成为日常的一小段停留。你可以写下心事，也可以什么都不解释，直接翻开一页。</p><h3>文字从哪里来</h3><p>书库现收入 1000 段诗词、古典文集章句和英文文学名言。每页附作者或编者、作品与来源；古典语料与公版汇编保留其版本异文，来源核对不等于独立完成古籍校勘。</p><h3>如何理解这些解读</h3><p>写下心事或选择支持情境后，由知乎直答理解你的表达，从带有来源的原文库选择书签并生成解读。AI 可能理解有误，解读不是作者原话，也不代表心理诊断。你可以不同意，或只读原文。直接选择纯阅读时，展示项目编辑解读。</p><p>书签根据这次表达匹配；没有合适原文时会直接说明。不预测未来，不提供心理诊断、治疗或紧急救援。</p></>}</div></DialogContent></Dialog>
 <Dialog open={!!detail} onOpenChange={open=>{if(!open)setDetail(null)}}><DialogContent className="reading-dialog max-w-[min(620px,calc(100%-32px))] p-8"><DialogTitle className="font-normal text-xl">{detail?.work||"原文"}</DialogTitle><DialogDescription>{detail?.author}</DialogDescription>{detail&&<div className="dialog-prose"><blockquote>{detail.text}</blockquote><span className="origin-badge">项目编辑解读</span><p>{detail.note}</p><Source q={detail}/></div>}</DialogContent></Dialog>
 </div>
}
